<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RuntimeIdentifiers>win-x64;win-x86;linux-x64;linux-x86;osx-x64</RuntimeIdentifiers>
    <KnownRuntimePack>
      <LatestRuntimeFrameworkVersion Condition="'%(TargetFramework)' == 'net8.0'">8.0.3</LatestRuntimeFrameworkVersion>
    </KnownRuntimePack> 
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.8.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Text.Json" Version="8.0.2" />
  </ItemGroup>

</Project>
